### ISSUE TITLE
The "date" header is mandatory

### ISSUE THREAD

**Issue by 4lador** [arkerone/api-key-auth#1]
#### Description
The "date" header is mandatory but it looks optional while reading the README.

> This options is used if HTTP header "date" is used to create the signature.

#### Screenshots
![image](https://user-images.githubusercontent.com/5941435/47311764-e39d8a80-d63a-11e8-8bc7-a93fcc49544f.png)

#### To Reproduce
Send any request without the date field

#### Tasks
- [ ] Add a mention in the README file

**Comment by 4lador** [comment]
Sorry, I finally found this information into the signature.md 👍 

> header (OPTIONAL) : The list of HTTP headers used to create the signature of the request. If specified, it should be a lowercased, quoted list of HTTP header fields, separated by a single space character. If not specified, the Date header is used by default therefore the client must send this Date header. Note : The list order is important, and must be specified in the order the HTTP header field-value pairs are concatenated together during signing.

**Comment by arkerone** [comment]
> Sorry, I finally found this information into the signature.md 👍
> 
> > header (OPTIONAL) : The list of HTTP headers used to create the signature of the request. If specified, it should be a lowercased, quoted list of HTTP header fields, separated by a single space character. If not specified, the Date header is used by default therefore the client must send this Date header. Note : The list order is important, and must be specified in the order the HTTP header field-value pairs are concatenated together during signing.

No problem ;)
