### ISSUE TITLE
new line \n causing issues

### ISSUE THREAD

**Issue by shenanigan** [arkerone/api-key-auth#2]
In the parser.js line 101 shouldn't the new line character be escaped?
Something like 
`signatureParams.signingString += '\\n';`

Without this I am always getting Bad signature for multiple headers. Everything works okay for 1 header

**Comment by arkerone** [comment]
How did you build your signature?

**Comment by shenanigan** [comment]
I used a couple of online tools to verify this:
1) https://www.freeformatter.com/hmac-generator.html
2) https://www.liavaag.org/English/SHA-Generator/HMAC/

**Comment by arkerone** [comment]
I don't know why this website have a problem to hash multiline string. Use this website : https://codebeautify.org/hmac-generator

**Comment by arkerone** [comment]
Ok this websites use the CF (0d) and LF (0a) for new line but we need only the LF (0a) represented by '\n'

**Comment by shenanigan** [comment]
Okay, Thanks will check it out and let you know.

**Comment by shenanigan** [comment]
It is working as per the website you pointed out.
